name: Alerta para arquivos maiores que 100kb
on:
push:
branches: [ main ]
jobs:
check-sizes:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Procurar arquivos maiores que 100KB
id: find_big
run: |
echo "Arquivos maiores que 100KB:"
mapfile -t bigs < <(find . -type f -size +100k -print)
if [ ${#bigs[@]} -eq 0 ]; then
echo "Nenhum arquivo acima de 100KB encontrado."
echo "has_big=false" >> $GITHUB_OUTPUT
else
for f in "${bigs[@]}"; do echo "$f"; done
echo "has_big=true" >> $GITHUB_OUTPUT
for f in "${bigs[@]}"; do
ls -lh "$f" || true
done
fi


- name: Falhar se houver arquivo grande (opcional)
if: steps.find_big.outputs.has_big == 'true'
run: |
echo "ALERTA: Há arquivos maiores que 100KB no push."
exit 1
