name: Alertar arquivos maiores que 100KB

on:
  push:
    branches: [ main ]

jobs:
  alerta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Procurar arquivos grandes
        run: |
          echo "Arquivos maiores que 100KB:"
          find . -type f -size +100k
