name: Criar README automático

on:
  push:
    branches: [ main ]

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Criar arquivo README
        run: |
          echo "# Projeto Automatizado" > README.md
          echo "Gerado automaticamente pelo GitHub Actions." >> README.md

      - name: Fazer commit e push do README
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Criado README automático" || echo "Nada para commitar"
          git push
