name: Listar arquivos do repositório

on:
  push:
    branches: [ main ]

jobs:
  listar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4
      - name: Listar arquivos
        run: ls -lh
