name: Info completa com sequência

on:
  push:
    branches: [ main ]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Data e hora
        run: date
      - name: Usuário
        run: echo "Usuário: ${{ github.actor }}"
      - name: Contagem de arquivos HTML
        run: echo "HTML: $(find . -type f -name '*.html' | wc -l)"
      - name: Contagem de arquivos CSS
        run: echo "CSS: $(find . -type f -name '*.css' | wc -l)"
      - name: Contagem de arquivos JS
        run: echo "JS: $(find . -type f -name '*.js' | wc -l)"
